### ISSUE TITLE
no plugin

### ISSUE THREAD

**Issue by cowboyab** [vininja/ClothTOP#2]
Hi vininja. Thanks for the the putting these files up for grabs. 
Being novice at compiling I have stubled trough the the setup.
I had to download visual studio in order to make thus run. Maybe a good note in your readme, if correct.

Anyway I ended up with a seemingly correct compilation in cmake, but with a red alert that 64 architecture was running. -and the plugin folder only containing a plugin text file with the contents:
{
    "Version": 1
}

You write about moving .dll files manually, but from where?
Any advice on what to do would be greatly appreciated.
Regards, Boya

**Comment by vininja** [comment]
Download the release .dll here [](https://github.com/vininja/ClothTOP/releases/tag/0.3)
